### ISSUE TITLE
SFML.Net support?

### ISSUE THREAD

**Issue by ghost** [EmptyKeys/UI_Engines#7]
Hello

Do you think you can add support for SFML C# binding?

That would be awesome!

Thanks

**Comment by EmptyKeys** [comment]
Hi, I was thinking about supporting some library like SFML or SkiaSharp etc. The problem is that I personally don't use those libraries and these libraries usually don't support all the features needed for UI out of the box (means you have to do something by yourself).

If you are using SFML.Net it would be cool if you can start with creating UI engine package for it. I can help you with details.

**Comment by ghost** [comment]
Would you do it if i pay you ? :D

**Comment by EmptyKeys** [comment]
I'm working full time on two projects, so not looking for any paid job at this moment. thanks tho
